### PR TITLE
corrected gelf information link (part 2)

### PR DESCRIPTION
**Pull request by janpieper**
Old: http://www.graylog2.org/gelf
New: http://www.graylog2.org/about/gelf

It's required to update your repository's description as well :-)

### CODE REVIEW

**Comment by janpieper** [comment]
huh? why is there another commit (23bdc0b)?

**Comment by AlekSi** [comment]
Looks like GitHub's bug.

**Comment by janpieper** [comment]
This is no patch for `master`! These changes are for the `newgelf` branch.

**Comment by lennartkoopmann** [comment]
Looks all good now - Also changed it in the repo description. Thank you!

**Pull request closed without merging**
